services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - pennsievedb-collections
    environment:
      - AWS_ACCESS_KEY_ID=TestAWSKey
      - AWS_SECRET_ACCESS_KEY=TestAWSSecret
      - POSTGRES_HOST=pennsievedb-collections
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_COLLECTIONS_DATABASE=postgres
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  pennsievedb-collections:
    image: pennsieve/pennsievedb-collections:20250327123104-seed
    restart: always
#    command: [ "postgres", "-c", "log_statement=all" ]

