FROM golang:1.23-alpine

WORKDIR /app

ENV CGO_ENABLED=0

COPY go.mod go.sum ./
RUN ["go", "mod", "download"]

COPY cmd cmd
COPY internal internal
#RUN ["go", "mod", "tidy"]
RUN ["go", "build", "-o", "/collections-dbmigrate", "cmd/dbmigrate/main.go"]

CMD ["/collections-dbmigrate"]
