package dto

var ValidLicenses = []string{
	`Apache 2.0`,
	`Apache License 2.0`,
	`BSD 2-Clause "Simplified" License`,
	`BSD 3-Clause "New" or "Revised" License`,
	`Boost Software License 1.0`,
	`Community Data License Agreement – Permissive`,
	`Community Data License Agreement – Sharing`,
	`Creative Commons Zero 1.0 Universal`,
	`Creative Commons Attribution`,
	`Creative Commons Attribution - ShareAlike`,
	`Creative Commons Attribution - NonCommercial-ShareAlike`,
	`Eclipse Public License 2.0`,
	`GNU Affero General Public License v3.0`,
	`GNU General Public License v2.0`,
	`GNU General Public License v3.0`,
	`GNU Lesser General Public License`,
	`GNU Lesser General Public License v2.1`,
	`GNU Lesser General Public License v3.0`,
	`MIT`,
	`MIT License`,
	`Mozilla Public License 2.0`,
	`Open Data Commons Open Database`,
	`Open Data Commons Attribution`,
	`Open Data Commons Public Domain Dedication and License`,
	`The Unlicense`,
}
